// AUTO-GENERATED BY generate-cloudinary-gallery-map.js
const gallery = {
  "corporate event": [
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045457/we-decor/corporate%20event/8D3A9822.jpg",
      "alt": "8D3A9822"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045455/we-decor/corporate%20event/IMG_20220813_195350.jpg",
      "alt": "IMG 20220813 195350"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045455/we-decor/corporate%20event/IMG_20220813_182017.jpg",
      "alt": "IMG 20220813 182017"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045453/we-decor/corporate%20event/8D3A9832.jpg",
      "alt": "8D3A9832"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045422/we-decor/corporate%20event/IMG_20230310_125952.jpg",
      "alt": "IMG 20230310 125952"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045421/we-decor/corporate%20event/IMG_20220706_015407.jpg",
      "alt": "IMG 20220706 015407"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045420/we-decor/corporate%20event/IMG_20221208_165717.jpg",
      "alt": "IMG 20221208 165717"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045418/we-decor/corporate%20event/IMG_20230310_125852.jpg",
      "alt": "IMG 20230310 125852"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045404/we-decor/corporate%20event/IMG20220706002702.heic",
      "alt": "IMG20220706002702"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045404/we-decor/corporate%20event/IMG20230311183341.jpg",
      "alt": "IMG20230311183341"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045401/we-decor/corporate%20event/IMG20220804220811.heic",
      "alt": "IMG20220804220811"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045395/we-decor/corporate%20event/IMG20220630214506.jpg",
      "alt": "IMG20220630214506"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045392/we-decor/corporate%20event/IMG20220804221030.heic",
      "alt": "IMG20220804221030"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045391/we-decor/corporate%20event/IMG20220623015558.jpg",
      "alt": "IMG20220623015558"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045385/we-decor/corporate%20event/IMG20220804232743.heic",
      "alt": "IMG20220804232743"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045384/we-decor/corporate%20event/IMG20220804220849.heic",
      "alt": "IMG20220804220849"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045384/we-decor/corporate%20event/IMG20220623015811.jpg",
      "alt": "IMG20220623015811"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045372/we-decor/corporate%20event/IMG20220630210013.jpg",
      "alt": "IMG20220630210013"
    }
  ],
  "engagement": [
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045457/we-decor/engagement/IMG_20220804_111702.jpg",
      "alt": "IMG 20220804 111702"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045456/we-decor/engagement/1664888637300.jpg",
      "alt": "1664888637300"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045455/we-decor/engagement/IMG_20220804_111849.jpg",
      "alt": "IMG 20220804 111849"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045450/we-decor/engagement/IMG_20220804_111707.jpg",
      "alt": "IMG 20220804 111707"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045446/we-decor/engagement/1672323160504.jpg",
      "alt": "1672323160504"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045440/we-decor/engagement/IMG_20220901_173447.jpg",
      "alt": "IMG 20220901 173447"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045433/we-decor/engagement/IMG20221225190848.jpg",
      "alt": "IMG20221225190848"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045426/we-decor/engagement/IMG_20221208_052732.jpg",
      "alt": "IMG 20221208 052732"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045425/we-decor/engagement/IMG_20230223_092722_1.jpg",
      "alt": "IMG 20230223 092722 1"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045421/we-decor/engagement/IMG_20220821_094856.jpg",
      "alt": "IMG 20220821 094856"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045405/we-decor/engagement/IMG_20221203_173403.jpg",
      "alt": "IMG 20221203 173403"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045403/we-decor/engagement/IMG20221029183904.jpg",
      "alt": "IMG20221029183904"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045400/we-decor/engagement/IMG20221225222312.jpg",
      "alt": "IMG20221225222312"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045388/we-decor/engagement/IMG_7522.heic",
      "alt": "IMG 7522"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045327/we-decor/engagement/IMG-20221118-WA0021.jpg",
      "alt": "IMG 20221118 WA0021"
    }
  ],
  "home decor": [
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045453/we-decor/home%20decor/IMG_20220822_085943_1.jpg",
      "alt": "IMG 20220822 085943 1"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045445/we-decor/home%20decor/IMG_20220822_090225.jpg",
      "alt": "IMG 20220822 090225"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045445/we-decor/home%20decor/IMG_20220726_180134.jpg",
      "alt": "IMG 20220726 180134"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045434/we-decor/home%20decor/IMG_20230223_105116.jpg",
      "alt": "IMG 20230223 105116"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045414/we-decor/home%20decor/IMG_20230223_092912_1.jpg",
      "alt": "IMG 20230223 092912 1"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045405/we-decor/home%20decor/IMG20220731112740_1.heic",
      "alt": "IMG20220731112740 1"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045402/we-decor/home%20decor/IMG_1996.heic",
      "alt": "IMG 1996"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045391/we-decor/home%20decor/IMG20220831040842.heic",
      "alt": "IMG20220831040842"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045388/we-decor/home%20decor/IMG20220831040547.heic",
      "alt": "IMG20220831040547"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045387/we-decor/home%20decor/IMG20220831040923.heic",
      "alt": "IMG20220831040923"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045381/we-decor/home%20decor/IMG20230219192512.jpg",
      "alt": "IMG20230219192512"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045363/we-decor/home%20decor/IMG20220831041153.heic",
      "alt": "IMG20220831041153"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045334/we-decor/home%20decor/IMG-20220808-WA0012.jpg",
      "alt": "IMG 20220808 WA0012"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045332/we-decor/home%20decor/IMG-20220808-WA0013.jpg",
      "alt": "IMG 20220808 WA0013"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045331/we-decor/home%20decor/IMG-20220808-WA0011.jpg",
      "alt": "IMG 20220808 WA0011"
    }
  ],
  "birthday": [
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045451/we-decor/birthday/313A0339.jpg",
      "alt": "313A0339"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045447/we-decor/birthday/IMG_20220903_190953.jpg",
      "alt": "IMG 20220903 190953"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045423/we-decor/birthday/IMG_20221122_172611.jpg",
      "alt": "IMG 20221122 172611"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045422/we-decor/birthday/IMG_20221220_175545.jpg",
      "alt": "IMG 20221220 175545"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045420/we-decor/birthday/IMG_20230213_181247.jpg",
      "alt": "IMG 20230213 181247"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045418/we-decor/birthday/IMG_20230130_175936.jpg",
      "alt": "IMG 20230130 175936"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045412/we-decor/birthday/IMG_20221210_172234.jpg",
      "alt": "IMG 20221210 172234"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045411/we-decor/birthday/IMG_20230208_191510.jpg",
      "alt": "IMG 20230208 191510"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045403/we-decor/birthday/IMG_20221119_123451.jpg",
      "alt": "IMG 20221119 123451"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045397/we-decor/birthday/IMG20221120193712.jpg",
      "alt": "IMG20221120193712"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045397/we-decor/birthday/IMG_20221206_171916.jpg",
      "alt": "IMG 20221206 171916"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045394/we-decor/birthday/IMG20230112224831.jpg",
      "alt": "IMG20230112224831"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045389/we-decor/birthday/IMG_20221008_190648.jpg",
      "alt": "IMG 20221008 190648"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045389/we-decor/birthday/IMG20221120105704.jpg",
      "alt": "IMG20221120105704"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045384/we-decor/birthday/IMG20220623160109.jpg",
      "alt": "IMG20220623160109"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045378/we-decor/birthday/IMG20221007201749.jpg",
      "alt": "IMG20221007201749"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045376/we-decor/birthday/IMG20221115011744.jpg",
      "alt": "IMG20221115011744"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045376/we-decor/birthday/IMG20221007170120.jpg",
      "alt": "IMG20221007170120"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045362/we-decor/birthday/IMG20220827202431.heic",
      "alt": "IMG20220827202431"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045352/we-decor/birthday/1666968820589.jpg",
      "alt": "1666968820589"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045337/we-decor/birthday/IMG20221001104927_2.heic",
      "alt": "IMG20221001104927 2"
    }
  ],
  "haldi": [
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045451/we-decor/haldi/1676444453828.jpg",
      "alt": "1676444453828"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045436/we-decor/haldi/IMG_20230127_163004.jpg",
      "alt": "IMG 20230127 163004"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045431/we-decor/haldi/IMG_20221211_093435_1.jpg",
      "alt": "IMG 20221211 093435 1"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045407/we-decor/haldi/IMG20220731112528.heic",
      "alt": "IMG20220731112528"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045402/we-decor/haldi/IMG20221117185438.jpg",
      "alt": "IMG20221117185438"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045399/we-decor/haldi/IMG20220721191332.heic",
      "alt": "IMG20220721191332"
    }
  ],
  "baby shower": [
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045414/we-decor/baby%20shower/IMG_20220731_111803.jpg",
      "alt": "IMG 20220731 111803"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045413/we-decor/baby%20shower/IMG20221030084105.jpg",
      "alt": "IMG20221030084105"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045402/we-decor/baby%20shower/IMG_20220731_105025.jpg",
      "alt": "IMG 20220731 105025"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045394/we-decor/baby%20shower/IMG_6746.heic",
      "alt": "IMG 6746"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045393/we-decor/baby%20shower/IMG20221030085036.jpg",
      "alt": "IMG20221030085036"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045383/we-decor/baby%20shower/IMG20221030095327_1.jpg",
      "alt": "IMG20221030095327 1"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045363/we-decor/baby%20shower/IMG20221016185451.jpg",
      "alt": "IMG20221016185451"
    }
  ],
  "room decor": [
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045381/we-decor/room%20decor/IMG_20250531_163833_1.jpg",
      "alt": "IMG 20250531 163833 1"
    },
    {
      "src": "https://res.cloudinary.com/dux3m2saz/image/upload/v1753045378/we-decor/room%20decor/IMG_20250531_163821_1.jpg",
      "alt": "IMG 20250531 163821 1"
    }
  ]
};

export default gallery;
